notifications:
  email:
    on_success: always
    on_failure: always

install:
 - npm install -g firebase-tools

script:
 - firebase deploy --project api-dartino-org-f30a3 --token "$FIREBASE_TOKEN"

after_success:
 - echo 'Succesfully deployed /public/ to https://api.dartino.org!'.
